class SongsController < ApplicationController

  def index
    @songs = Song.all
  end

  def show
    @song=Song.find(params[:id])
  end
  #****************
  def edit
    @song=Song.find(params[:id])
  end

  def update
    @song=Song.find(params[:id])
    if @song.update(song_params(:title))
      redirect_to song_path(@song)
    else
      render :edit
    end #
  end
  # **************
    def new
      @song=Song.new
    end

    def create
      @song=Song.new(song_params(:song))
      if @song. valid?#create(song_params(:title))
        @song.save
        redirect_to song_path(@song)
      else
        render :new
      end
    end
  # **************

  # def destroy
  #   Person.find(params[:id]).destroy
  #   redirect_to people_url
  # end
  def destroy
    Song.find(params[:id]).destroy
    redirect_to songs_path
  end

  private

  def song_params(*args)
    params.require(:song).permit(:title,:released,:release_year,:artist_name,:genre)
  end

end
#
# <!--# app/controllers/people_controller.rb-->
# def destroy
#   Person.find(params[:id]).destroy
#   redirect_to people_url
# end
# <!-- app/views/people/index.html.erb //-->
# <% @people.each do |person| %>
# <div class="person">
#   <span><%= person.name %></span>
#   <%= link_to "Delete", person, method: :delete, data: { confirm: "Really?" } %>
# </div>
# <% end %>
# #The HTML generated by that call to link_to looks like this:
# ##<a data-confirm="Really?" rel="nofollow" data-method="delete" href="/people/1">Delete</a>
